In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:
!apt-get update
!apt-get install g++ openjdk-8-jdk

!pip install JPype1
!pip install rhinoMorph

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:7 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:10 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Get:14 http://archive.ubuntu.com/ubuntu bionic-upd

In [3]:
path="/content/gdrive/MyDrive/pytest/"
def read_data(filename, encoding='cp949'): 
  with open(filename, 'r', encoding=encoding) as f:
    data = [line.split('\t') for line in f.read().splitlines()]
    data = data[1:] 
  return data
def write_data(data, filename, encoding='cp949'):
  with open(filename, 'w', encoding=encoding) as f:
    f.write(data)

In [4]:
data = read_data(path+'ratings_morphed.txt' , encoding='cp949')

In [5]:
print(type(data))

<class 'list'>


In [6]:
print(len(data))

197559


In [7]:
import random
import math
import numpy as np
random.shuffle(data)

part_num=math.floor(len(data)*1/3)
data=data[:part_num]
print(len(data))

65853


In [8]:
data_text=[line[1] for line in data]
data_senti=[line[2]for line in data]

In [9]:
from sklearn.model_selection import train_test_split
train_data_text, test_data_text, train_data_senti, test_data_senti = train_test_split(data_text, data_senti, stratify=data_senti)

In [10]:
from collections import Counter

In [11]:
train_data_senti_freq=Counter(train_data_senti)

In [12]:
test_data_senti_freq=Counter(test_data_senti)

In [13]:
print('test_data_senti_freq:', test_data_senti_freq)

test_data_senti_freq: Counter({'1': 8257, '0': 8207})


In [14]:
import numpy as np
text_len=[len(line.split(' ')) for line in train_data_text]
print("최소길이: ", np.min(text_len))

최소길이:  1


In [15]:
print("평균길이: ",np.round(np.mean(text_len),1))

평균길이:  8.9


In [16]:
print("최소길이 문장: ", train_data_text[np.argmin(text_len)])
print("최대길이 문장: ", train_data_text[np.argmax(text_len)])


최소길이 문장:  최고
최대길이 문장:  ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ ㅋㅋ


In [17]:
print("최소길이: ", np.min(text_len)) # 1
print("최대길이: ", np.max(text_len)) # 70
print("평균길이: ", np.round(np.mean(text_len), 1)) # 8.8
print("중위수길이: ", np.median(text_len)) # 7.7
print("구간별 최대 길이: ", np.percentile(text_len, [0, 25, 50, 75, 90, 100]))


최소길이:  1
최대길이:  70
평균길이:  8.9
중위수길이:  7.0
구간별 최대 길이:  [ 1.  4.  7. 11. 19. 70.]


In [18]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np
import math

In [19]:
max_words=10000
max_len=20

In [20]:
tokenizer=Tokenizer(num_words=max_words)

In [21]:
tokenizer.fit_on_texts(train_data_text)

In [22]:
word_index=tokenizer.word_index

In [23]:
print('전체에서 %s개의 고유한 토큰을 찾았습니다.' %len(word_index))

전체에서 22428개의 고유한 토큰을 찾았습니다.


In [24]:
word_index

{'영화': 1,
 '하다': 2,
 '보다': 3,
 '없다': 4,
 'ㅋㅋ': 5,
 '재미있다': 6,
 '좋다': 7,
 '너무': 8,
 '되다': 9,
 '있다': 10,
 '정말': 11,
 '같다': 12,
 '진짜': 13,
 '만들다': 14,
 '나오다': 15,
 '연기': 16,
 '최고': 17,
 '평점': 18,
 'ㅋ': 19,
 '다': 20,
 '이': 21,
 '잘': 22,
 '이런': 23,
 '왜': 24,
 '안': 25,
 '스토리': 26,
 '알다': 27,
 '더': 28,
 '때': 29,
 '드라마': 30,
 '주다': 31,
 '사람': 32,
 '지루': 33,
 '내용': 34,
 '생각': 35,
 '말': 36,
 '좀': 37,
 '아깝다': 38,
 '감독': 39,
 '그냥': 40,
 '재미': 41,
 '재미없다': 42,
 '시간': 43,
 'ㅠㅠ': 44,
 '감동': 45,
 '가다': 46,
 '쓰레기': 47,
 '모르다': 48,
 '다시': 49,
 '배우': 50,
 '작품': 51,
 '말다': 52,
 '아': 53,
 '처음': 54,
 '액션': 55,
 '사랑': 56,
 '마지막': 57,
 '들다': 58,
 '많다': 59,
 '완전': 60,
 '못하다': 61,
 '그': 62,
 '이야기': 63,
 '정도': 64,
 '느끼다': 65,
 '못': 66,
 '지금': 67,
 '이렇게': 68,
 '장면': 69,
 '느낌': 70,
 '10점': 71,
 '돈': 72,
 '최악': 73,
 '별로': 74,
 '오다': 75,
 'ㅎㅎ': 76,
 '무슨': 77,
 '쓰다': 78,
 '이것다': 79,
 '보이다': 80,
 '좋아하다': 81,
 '끝': 82,
 '역시': 83,
 '그리고': 84,
 '마음': 85,
 '주인공': 86,
 '참': 87,
 '여자': 88,
 '남다': 89,
 '또': 90,
 'ㅠ': 91,
 '괜

In [25]:
data=tokenizer.texts_to_sequences(train_data_text)
print('data 0:', data[0])
print('texts 0:', train_data_text[0])


data 0: [4309, 442]
texts 0: 에혀 ㅇ


## One-Hot-Encoding.ipynb

In [26]:
sample=[[5,6,7],[8,9,10]]
arr=np.zeros((len(sample),10+1))

In [27]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
for i, seq in enumerate(sample):
  arr[i,seq]=1.

In [30]:
arr

array([[0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [32]:
def to_one_hot(sequences, dimension):
  results = np.zeros((len(sequences), dimension))
  for i, sequence in enumerate(sequences):
   results[i, sequence] = 1.
  return results

In [33]:
data = to_one_hot(data, dimension=max_words) 
labels = np.asarray(train_data_senti).astype('float32')

In [34]:
data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
data[5,:20]

array([0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [42]:
word_index

{'영화': 1,
 '하다': 2,
 '보다': 3,
 '없다': 4,
 'ㅋㅋ': 5,
 '재미있다': 6,
 '좋다': 7,
 '너무': 8,
 '되다': 9,
 '있다': 10,
 '정말': 11,
 '같다': 12,
 '진짜': 13,
 '만들다': 14,
 '나오다': 15,
 '연기': 16,
 '최고': 17,
 '평점': 18,
 'ㅋ': 19,
 '다': 20,
 '이': 21,
 '잘': 22,
 '이런': 23,
 '왜': 24,
 '안': 25,
 '스토리': 26,
 '알다': 27,
 '더': 28,
 '때': 29,
 '드라마': 30,
 '주다': 31,
 '사람': 32,
 '지루': 33,
 '내용': 34,
 '생각': 35,
 '말': 36,
 '좀': 37,
 '아깝다': 38,
 '감독': 39,
 '그냥': 40,
 '재미': 41,
 '재미없다': 42,
 '시간': 43,
 'ㅠㅠ': 44,
 '감동': 45,
 '가다': 46,
 '쓰레기': 47,
 '모르다': 48,
 '다시': 49,
 '배우': 50,
 '작품': 51,
 '말다': 52,
 '아': 53,
 '처음': 54,
 '액션': 55,
 '사랑': 56,
 '마지막': 57,
 '들다': 58,
 '많다': 59,
 '완전': 60,
 '못하다': 61,
 '그': 62,
 '이야기': 63,
 '정도': 64,
 '느끼다': 65,
 '못': 66,
 '지금': 67,
 '이렇게': 68,
 '장면': 69,
 '느낌': 70,
 '10점': 71,
 '돈': 72,
 '최악': 73,
 '별로': 74,
 '오다': 75,
 'ㅎㅎ': 76,
 '무슨': 77,
 '쓰다': 78,
 '이것다': 79,
 '보이다': 80,
 '좋아하다': 81,
 '끝': 82,
 '역시': 83,
 '그리고': 84,
 '마음': 85,
 '주인공': 86,
 '참': 87,
 '여자': 88,
 '남다': 89,
 '또': 90,
 'ㅠ': 91,
 '괜

In [43]:
print(type(train_data_text))

<class 'list'>


In [44]:
print(type(data))

<class 'numpy.ndarray'>


In [45]:
print(data.shape)

(49389, 10000)


In [46]:
validation_ratio = 0.3 
validation_len = math.floor(len(train_data_text) * validation_ratio) 
x_train = data[validation_len:] 
y_train = labels[validation_len:] 
x_val = data[:validation_len]
y_val = labels[:validation_len] 

#모델설계

In [47]:
from keras.models import Sequential
from keras.layers import Dense

In [48]:
model=Sequential()

model = Sequential([

    Dense(32, input_shape=(784,)), # 클래스32

    Activation('relu'),             # 선형 함수

    Dense(10),                       # 클래스 10

    Activation('softmax'),

])

 

In [49]:
model.add(Dense(64, activation='relu', input_shape=(max_words,))) 
model.add(Dense(32, activation='relu')) 
model.add(Dense(1, activation='sigmoid'))

In [50]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                640064    
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 642,177
Trainable params: 642,177
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_val, y_val))
history_dict = history.history

Epoch 1/5
1081/1081 [==============================] - 15s 13ms/step - loss: 0.4313 - acc: 0.8049 - val_loss: 0.4086 - val_acc: 0.8186
Epoch 2/5
1081/1081 [==============================] - 12s 11ms/step - loss: 0.3648 - acc: 0.8426 - val_loss: 0.4043 - val_acc: 0.8224
Epoch 3/5
1081/1081 [==============================] - 12s 11ms/step - loss: 0.3464 - acc: 0.8542 - val_loss: 0.4010 - val_acc: 0.8251
Epoch 4/5
1081/1081 [==============================] - 12s 11ms/step - loss: 0.3326 - acc: 0.8620 - val_loss: 0.3999 - val_acc: 0.8244
Epoch 5/5
1081/1081 [==============================] - 12s 11ms/step - loss: 0.3201 - acc: 0.8687 - val_loss: 0.4096 - val_acc: 0.8244
